######################################################################
# Automatically generated by qmake (3.1) Tue Feb 21 20:55:05 2017
######################################################################

# We need QupZilla source
qupzilla_src_dir = $$(QUPZILLA_SRCDIR)
equals(qupzilla_src_dir, "") {
    include(../../../plugins.pri)
}
else {
    include($$qupzilla_src_dir/src/plugins.pri)
}

# Overriding definitions for tests
DEFINES += VIM_PLUGIN_TESTS
!mac:unix {
    DEFINES += LIB_VIM_PLUGIN=\\\"""$$DESTDIR/libVimPlugin.so"\\\""
}
mac {
    DEFINES += LIB_VIM_PLUGIN=\\\"""$$DESTDIR/libVimPlugin.dylib"\\\""
}

QT += webenginewidgets testlib
TEMPLATE = app
TARGET = VimPluginTests

CONFIG += testcase

OBJECTS_DIR = ../build
MOC_DIR = ../build
RCC_DIR = ../build
DESTDIR = ../build

HEADERS += ../include/VimPlugin.h \
           ../include/VimEngine.h

SOURCES += VimPluginTests.cpp   \
           ../src/VimPlugin.cpp \
           ../src/VimEngine.cpp

INCLUDEPATH += $$PWD/../include/                        \
               $$qupzilla_src_dir/src/lib/adblock       \
               $$qupzilla_src_dir/src/lib/app           \
               $$qupzilla_src_dir/src/lib/autofill      \
               $$qupzilla_src_dir/src/lib/bookmarks     \
               $$qupzilla_src_dir/src/lib/cookies       \
               $$qupzilla_src_dir/src/lib/downloads     \
               $$qupzilla_src_dir/src/lib/history       \
               $$qupzilla_src_dir/src/lib/navigation    \
               $$qupzilla_src_dir/src/lib/network       \
               $$qupzilla_src_dir/src/lib/notifications \
               $$qupzilla_src_dir/src/lib/opensearch    \
               $$qupzilla_src_dir/src/lib/other         \
               $$qupzilla_src_dir/src/lib/plugins       \
               $$qupzilla_src_dir/src/lib/popupwindow   \
               $$qupzilla_src_dir/src/lib/preferences   \
               $$qupzilla_src_dir/src/lib/rss           \
               $$qupzilla_src_dir/src/lib/session       \
               $$qupzilla_src_dir/src/lib/sidebar       \
               $$qupzilla_src_dir/src/lib/tabwidget     \
               $$qupzilla_src_dir/src/lib/tools         \
               $$qupzilla_src_dir/src/lib/webengine     \
               $$qupzilla_src_dir/src/lib/webtab        \
               $$qupzilla_src_dir/src/lib/3rdparty      \

DEPENDPATH += $$INCLUDEPATH                      \
              $$qupzilla_src_dir/src/lib/data    \
